"use client"

// NOTE: This component is generated by chakra-cli

import type { HTMLChakraProps, RecipeProps } from "@chakra-ui/react"
import { createRecipeContext } from "@chakra-ui/react"

export type LinkButtonProps = HTMLChakraProps<"a", RecipeProps<"button">>

const { withContext } = createRecipeContext({ key: "button" })

// Replace "a" with your framework's link component
export const LinkButton = withContext<HTMLAnchorElement, LinkButtonProps>("a")
